import type { LangStack, ModuleSpec } from "./schema";

function pascal(slug: string) {
  return slug
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join("");
}

export type CodeFile = { path: string; language: string; code: string };

function fieldList(spec: ModuleSpec) {
  const form = spec.screens.find((s) => s.type === "form") ?? spec.screens[0]!;
  return form.fields.length ? form.fields : spec.entities[0]?.fields ?? [];
}

export function generateReactCode(spec: ModuleSpec): string {
  const name = pascal(spec.slug);
  const fields = fieldList(spec);
  const state = fields
    .map((f) => `  const [${f.name}, set${pascal(f.name)}] = useState(${f.type === "checkbox" ? "false" : '""'});`)
    .join("\n");
  const inputs = fields
    .map((f) => {
      if (f.type === "select") {
        const opts = (f.options ?? ["Option A", "Option B"])
          .map((o) => `            <option value="${o}">${o}</option>`)
          .join("\n");
        return `        <label className="grid gap-1 text-sm">
          ${f.label}${f.required ? " *" : ""}
          <select value={${f.name}} onChange={(e) => set${pascal(f.name)}(e.target.value)} className="h-10 rounded-md border px-3">
            <option value="">Select</option>
${opts}
          </select>
        </label>`;
      }
      if (f.type === "textarea") {
        return `        <label className="grid gap-1 text-sm">
          ${f.label}
          <textarea value={${f.name}} onChange={(e) => set${pascal(f.name)}(e.target.value)} className="min-h-24 rounded-md border px-3 py-2" />
        </label>`;
      }
      if (f.type === "checkbox") {
        return `        <label className="flex items-center gap-2 text-sm">
          <input type="checkbox" checked={${f.name}} onChange={(e) => set${pascal(f.name)}(e.target.checked)} />
          ${f.label}
        </label>`;
      }
      return `        <label className="grid gap-1 text-sm">
          ${f.label}${f.required ? " *" : ""}
          <input type="${f.type === "date" ? "date" : f.type === "number" ? "number" : "text"}" value={${f.name}} onChange={(e) => set${pascal(f.name)}(e.target.value)} className="h-10 rounded-md border px-3" />
        </label>`;
    })
    .join("\n");
  const payload = fields.map((f) => `          ${f.name},`).join("\n");
  return `import { useState } from "react";

/** Generated by Sutra — ${spec.name} */
export function ${name}Form() {
${state}
  const [status, setStatus] = useState("");

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    const res = await fetch("${spec.apis.find((a) => a.method === "POST")?.path ?? `/api/${spec.slug}`}", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
${payload}
      }),
    });
    setStatus(res.ok ? "Submitted" : "Failed");
  }

  return (
    <form onSubmit={onSubmit} className="mx-auto grid max-w-xl gap-4 p-6">
      <h1 className="text-2xl font-semibold">${spec.name}</h1>
      <p className="text-sm opacity-70">${spec.summary}</p>
${inputs}
      <button type="submit" className="h-10 rounded-md bg-neutral-900 text-white">Submit</button>
      {status ? <p>{status}</p> : null}
    </form>
  );
}
`;
}

export function generateApiCode(spec: ModuleSpec): string {
  const routes = spec.apis
    .map((api) => {
      const method = api.method.toLowerCase();
      if (api.method === "GET") {
        return `app.get("${api.path}", (_req, res) => {
  // ${api.purpose} · role: ${api.role}
  res.json({ ok: true, data: store.list() });
});`;
      }
      return `app.${method}("${api.path}", (req, res) => {
  // ${api.purpose} · role: ${api.role}
  const row = store.save(req.body);
  res.status(201).json({ ok: true, data: row });
});`;
    })
    .join("\n\n");
  return `import express from "express";

/** Generated by Sutra IDE — ${spec.name} */
const app = express();
app.use(express.json());

const store = {
  rows: [],
  list() { return this.rows; },
  save(body) {
    const row = { id: crypto.randomUUID(), ...body };
    this.rows.unshift(row);
    return row;
  },
};

${routes}

app.listen(3000, () => console.log("${spec.slug} API on :3000"));
`;
}

function pyFields(spec: ModuleSpec) {
  return fieldList(spec)
    .map((f) => `    ${f.name}: ${f.type === "number" ? "float" : f.type === "checkbox" ? "bool" : "str"}`)
    .join("\n");
}

function generatePython(spec: ModuleSpec): CodeFile[] {
  const fields = pyFields(spec);
  const routes = spec.apis
    .map((a) => {
      const fn = a.method === "GET" ? "list_items" : "create_item";
      if (a.method === "GET") {
        return `@app.get("${a.path}")
def ${fn}():
    """${a.purpose}"""
    return store`;
      }
      return `@app.post("${a.path}")
def ${fn}(item: Item):
    """${a.purpose}"""
    row = item.model_dump()
    row["id"] = str(len(store) + 1)
    store.append(row)
    return row`;
    })
    .join("\n\n");
  return [
    {
      path: `src/${spec.slug}/models.py`,
      language: "python",
      code: `from pydantic import BaseModel

class Item(BaseModel):
${fields || "    name: str"}
`,
    },
    {
      path: `src/${spec.slug}/main.py`,
      language: "python",
      code: `from fastapi import FastAPI
from .models import Item

app = FastAPI(title="${spec.name}")
store: list[dict] = []

${routes}
`,
    },
  ];
}

function generateJava(spec: ModuleSpec): CodeFile[] {
  const name = pascal(spec.slug);
  const fields = fieldList(spec)
    .map((f) => `    private ${f.type === "number" ? "Double" : f.type === "checkbox" ? "Boolean" : "String"} ${f.name};`)
    .join("\n");
  const mappings = spec.apis
    .map((a) => {
      if (a.method === "GET") {
        return `    @GetMapping("${a.path}")
    public List<${name}> list() { return store; }`;
      }
      return `    @PostMapping("${a.path}")
    public ${name} create(@RequestBody ${name} body) { store.add(body); return body; }`;
    })
    .join("\n\n");
  return [
    {
      path: `src/main/java/${name}.java`,
      language: "java",
      code: `public class ${name} {
${fields}
    // getters/setters
}
`,
    },
    {
      path: `src/main/java/${name}Controller.java`,
      language: "java",
      code: `import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
public class ${name}Controller {
    private final List<${name}> store = new ArrayList<>();

${mappings}
}
`,
    },
  ];
}

function generateGo(spec: ModuleSpec): CodeFile[] {
  const fields = fieldList(spec)
    .map((f) => `\t${pascal(f.name)} ${f.type === "number" ? "float64" : "string"} \`json:"${f.name}"\``)
    .join("\n");
  const routes = spec.apis
    .map((a) => `    r.${a.method === "GET" ? "GET" : "POST"}("${a.path}", handle)`)
    .join("\n");
  return [
    {
      path: `src/${spec.slug}/model.go`,
      language: "go",
      code: `package main

type Item struct {
${fields}
}
`,
    },
    {
      path: `src/${spec.slug}/main.go`,
      language: "go",
      code: `package main

import (
    "encoding/json"
    "net/http"
)

var store []Item

func handle(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("Content-Type", "application/json")
    if r.Method == http.MethodGet {
        json.NewEncoder(w).Encode(store)
        return
    }
    var item Item
    json.NewDecoder(r.Body).Decode(&item)
    store = append(store, item)
    json.NewEncoder(w).Encode(item)
}

func main() {
    mux := http.NewServeMux()
    _ = mux
${routes}
    http.ListenAndServe(":8080", nil)
}
`,
    },
  ];
}

function generateCsharp(spec: ModuleSpec): CodeFile[] {
  const name = pascal(spec.slug);
  const fields = fieldList(spec)
    .map((f) => `    public ${f.type === "number" ? "double" : "string"} ${pascal(f.name)} { get; set; }`)
    .join("\n");
  return [
    {
      path: `src/${name}.cs`,
      language: "csharp",
      code: `public class ${name} {
${fields}
}
`,
    },
    {
      path: `src/${name}Controller.cs`,
      language: "csharp",
      code: `using Microsoft.AspNetCore.Mvc;

[ApiController]
public class ${name}Controller : ControllerBase {
    static readonly List<${name}> Store = new();

    [HttpGet("/api/${spec.slug}")]
    public IActionResult List() => Ok(Store);

    [HttpPost("/api/${spec.slug}")]
    public IActionResult Create([FromBody] ${name} body) {
        Store.Add(body);
        return Ok(body);
    }
}
`,
    },
  ];
}

function generatePhp(spec: ModuleSpec): CodeFile[] {
  return [
    {
      path: `src/${spec.slug}/Item.php`,
      language: "php",
      code: `<?php
class Item {
    public function __construct(public array $data) {}
}
`,
    },
    {
      path: `public/index.php`,
      language: "php",
      code: `<?php
header("Content-Type: application/json");
$store = [];
$method = $_SERVER["REQUEST_METHOD"];
if ($method === "GET") {
    echo json_encode($store);
    return;
}
$body = json_decode(file_get_contents("php://input"), true);
$store[] = $body;
echo json_encode($body);
`,
    },
  ];
}

function generateRust(spec: ModuleSpec): CodeFile[] {
  const fields = fieldList(spec)
    .map((f) => `    pub ${f.name}: ${f.type === "number" ? "f64" : "String"},`)
    .join("\n");
  return [
    {
      path: `src/model.rs`,
      language: "rust",
      code: `use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
pub struct Item {
${fields || "    pub name: String,"}
}
`,
    },
    {
      path: `src/main.rs`,
      language: "rust",
      code: `use axum::{Json, Router, routing::{get, post}};
mod model;
use model::Item;
use std::sync::Mutex;

static STORE: Mutex<Vec<Item>> = Mutex::new(Vec::new());

async fn list() -> Json<Vec<Item>> {
    Json(STORE.lock().unwrap().clone())
}

async fn create(Json(item): Json<Item>) -> Json<Item> {
    STORE.lock().unwrap().push(item.clone());
    Json(item)
}

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/api/${spec.slug}", get(list).post(create));
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
`,
    },
  ];
}

function generateRuby(spec: ModuleSpec): CodeFile[] {
  return [
    {
      path: `app/models/item.rb`,
      language: "ruby",
      code: `class Item
  attr_accessor ${fieldList(spec).map((f) => `:${f.name}`).join(", ") || ":name"}
end
`,
    },
    {
      path: `config/routes.rb`,
      language: "ruby",
      code: `require "sinatra"
require "json"

store = []

get "/api/${spec.slug}" do
  content_type :json
  store.to_json
end

post "/api/${spec.slug}" do
  content_type :json
  body = JSON.parse(request.body.read)
  store << body
  body.to_json
end
`,
    },
  ];
}

function generateKotlin(spec: ModuleSpec): CodeFile[] {
  const name = pascal(spec.slug);
  const fields = fieldList(spec)
    .map((f) => `    val ${f.name}: ${f.type === "number" ? "Double" : "String"}`)
    .join(",\n");
  return [
    {
      path: `src/main/kotlin/${name}.kt`,
      language: "kotlin",
      code: `data class ${name}(
${fields}
)
`,
    },
    {
      path: `src/main/kotlin/${name}Routes.kt`,
      language: "kotlin",
      code: `import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Route.${spec.slug.replace(/-/g, "")}() {
    val store = mutableListOf<${name}>()
    get("/api/${spec.slug}") { call.respond(store) }
    post("/api/${spec.slug}") {
        val body = call.receive<${name}>()
        store += body
        call.respond(body)
    }
}
`,
    },
  ];
}

const STACK_FILES: Record<LangStack, (spec: ModuleSpec) => CodeFile[]> = {
  "react-node": (spec) => [
    { path: `src/modules/${spec.slug}/${pascal(spec.slug)}Form.tsx`, language: "tsx", code: generateReactCode(spec) },
    { path: `src/server/${spec.slug}.ts`, language: "ts", code: generateApiCode(spec) },
  ],
  python: generatePython,
  java: generateJava,
  go: generateGo,
  csharp: generateCsharp,
  php: generatePhp,
  rust: generateRust,
  ruby: generateRuby,
  kotlin: generateKotlin,
};

export function generateFiles(spec: ModuleSpec): CodeFile[] {
  const stack = spec.stack ?? "react-node";
  return (STACK_FILES[stack] ?? STACK_FILES["react-node"])(spec);
}

export function stackLabel(stack: LangStack) {
  return {
    "react-node": "React + Node",
    python: "Python (FastAPI)",
    java: "Java (Spring)",
    go: "Go",
    csharp: "C# (.NET)",
    php: "PHP",
    rust: "Rust (Axum)",
    ruby: "Ruby (Sinatra)",
    kotlin: "Kotlin (Ktor)",
  }[stack];
}
